### ISSUE TITLE
UAV-Search Setup steps

### ISSUE THREAD

**Issue by enginksz** [AhmedHisham1/UAV-Search#2]
Hello,

We can't see everything in the video you shared.
( https://www.youtube.com/watch?v=-0mwb_KjFy8&t=133s )
( https://www.youtube.com/watch?v=lc4bMRS7228)

We will be glad if you explain step by step.

e.g.
Here's what to do for gazebo: XXX~/PX4-Autopilot$ make px4_sitl_default gazebo
Could you also attach the .launch file of the Gazebo environment? Because your world file does not come by default in gazebo_sitl.
Here's what to do for object detection: (your code) XXX~/UAV$ python main.py
For the QGroundControl interface, this is what needs to be done: ./QGroundControl.AppImage
For mavros initialization the following is required: roslaunch mavros px4.launch fcu_url:="udp://:14540@localhost:14557"

Because I am getting errors while executing main.py file.

engin@engin:/UAV-Search$ python main.py
Traceback (most recent call last):
File "main.py", line 19, in
from cv_utils import coordinates_plot, draw_outputs, keep_person_only, localize_person
File "/home/engin/UAV-Search/cv_utils.py", line 4, in
from mavsdk_utils import get_location_offset_meters
File "/home/engin/UAV-Search/mavsdk_utils.py", line 2, in
from mavsdk import System, MissionItem, OffboardError, PositionNedYaw, Action
ImportError: cannot import name 'MissionItem' from 'mavsdk' (/usr/local/lib/python3.8/dist-packages/mavsdk/init.py)

**Comment by enginksz** [comment]
I fixed.

Failed :from mavsdk import System, MissionItem, OffboardError, PositionNedYaw, Action 

It is 
from mavsdk.offboard import OffboardError , PositionNedYaw
from mavsdk.action import Action
from mavsdk.mission import MissionItem
from mavsdk import System 

from mavsdk_utils import connect_sitl, get_relative_altitude, get_euler_angles, get_lat_lon, land, square_mission, square_mission_offboard, path_mission
import asyncio

**Comment by enqinn** [comment]
but; I find it quite difficult to run the simulation. Maybe you could show us how to run your simulation @AhmedHisham1 ? Thank you.

**Comment by enqinn** [comment]
![Screenshot from 2022-04-17 01-26-48](https://user-images.githubusercontent.com/38870269/163693223-b3eef989-62b4-45a2-a381-a40b848cc549.png)

**Comment by enqinn** [comment]
> but; I find it quite difficult to run the simulation. Maybe you could show us how to run your simulation @AhmedHisham1 ? Thank you.
